declare module 'vue2-dropzone'
declare module 'sortablejs'
declare module 'vue-headful'
declare module 'vue-grid-layout'
declare module 'vue-infinite-scroll'
declare module 'vue-quill-editor'
declare module 'quill-image-resize-module'
